### ISSUE TITLE
clients for Molecular Interaction data and iRefIndex

### ISSUE THREAD

**Issue by abotzki** [vibbits/irefindex-cli#1]
- https://irefindex.vib.be/wiki/index.php/PSICQUIC

- https://psicquic.github.io/ and https://psicquic.github.io/PsicquicSpec_1_4_Rest.html
   https://psicquic.github.io/Clients.html

- R client for iRefIndex specifically
  https://cran.r-project.org/package=iRefR
  this client has been removed since it is no longer supported by https://github.com/antonio-mora/iRefR

**Comment by MaybeJustJames** [comment]
Exaple queries:
`https://irefindex.vib.be/psicquic/webservices/current/search/query/taxid:2697049`
`https://irefindex.vib.be/psicquic/webservices/current/search/query/edgetype:C`

Documentation:
* https://irefindex.vib.be/wiki/index.php/README_MITAB2.6_for_iRefIndex_18.0
* https://irefindex.vib.be/webservices/current?_wadl
* https://psicquic.github.io/MiqlReference28.html

**Comment by MaybeJustJames** [comment]
Closing. Effort moving to a web client
